export const dogs = [
    {
        id: 1,
        name: 'Sir Fluffington III',
        age: '8 weeks',
        gender: 'Male',
        price: '£1,200',
        desc: 'A distinguished gentleman with a spectacular fringe and zero interest in following rules.',
        tag: 'Available',
    },
    {
        id: 2,
        name: 'Tiny Menace',
        age: '10 weeks',
        gender: 'Female',
        price: '£1,350',
        desc: 'Do not let the size fool you. She has already claimed the sofa, the remote, and your heart.',
        tag: 'Available',
    },
    {
        id: 3,
        name: 'Lord Barksworth',
        age: '9 weeks',
        gender: 'Male',
        price: '£1,200',
        desc: 'Barks at clouds. Barks at shadows. Barks at the concept of silence. An absolute delight.',
        tag: 'Available',
    },
    {
        id: 4,
        name: 'Princess Havoc',
        age: '8 weeks',
        gender: 'Female',
        price: '£1,400',
        desc: 'She entered the room and immediately knocked something off the table on purpose. We respect it.',
        tag: 'Reserved',
    },
    {
        id: 5,
        name: 'Mister Wobble',
        age: '11 weeks',
        gender: 'Male',
        price: '£1,150',
        desc: 'Runs full speed into walls and gets up wagging. The most optimistic creature alive.',
        tag: 'Available',
    },
    {
        id: 6,
        name: 'Countess Snugglepaws',
        age: '9 weeks',
        gender: 'Female',
        price: '£1,350',
        desc: 'Sleeps 22 hours a day and spends the other two causing irreversible emotional damage to your schedule.',
        tag: 'Available',
    },
]
